#!/usr/bin/env python3
# ============================================================================
# convert_flight.py — flight_data.csv → hil_panel/flight_trajectory.js
# Cursr-V Antenna Tracker · HIL flight-replay converter (one-off, host-side)
#
# Reads the local-Cartesian rocket flight log and emits a resampled trajectory
# the Mission Console streams to the firmware as `track` telemetry.
#
#   X (m) → East,  Y (m) → North,  Z (m) → Up (MSL)
#   Launch pad sits 700 m North / 200 m East of the tracker:
#       e = 200 + X,  n = 700 + Y,  u = Z - 892   (892 m = launch ground level)
#
# Output samples carry both the local ENU offset (e,n,u — what gets streamed)
# and a reference WGS84 fix (lat,lon,alt — a "truth" trace for the panel),
# resampled to a fixed cadence so playback is even (the raw rows are sub-ms
# dense at ignition, seconds apart near apogee).
#
# NOTE: the plan specified a Node `.mjs`; this project's host has Python but not
# Node, so the converter is Python. The emitted flight_trajectory.js is identical
# either way (the panel only consumes the generated JS).
#
#   python tools/convert_flight.py
# ============================================================================
import csv
import math
import os

HZ = 15                       # fixed resample cadence (must match TRACK_STREAM_HZ)
OFFSET_E = 200.0              # launch pad east of tracker  (m)
OFFSET_N = 700.0             # launch pad north of tracker (m)
GROUND_Z = 892.0             # launch-site ground level    (m MSL)

# Base station = launch site (reuse config.h HIL_DEFAULT_BASE_LAT/LON).
BASE_LAT = 13.7563
BASE_LON = 100.5018
BASE_ALT = GROUND_Z

M_PER_DEG = 111320.0         # flat-earth metres per degree of latitude

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_IN = os.path.join(REPO, "flight_data.csv")
JS_OUT = os.path.join(REPO, "hil_panel", "flight_trajectory.js")


def az_el(e, n, u):
    """Pointing angles from base to a local ENU point (degrees)."""
    az = math.degrees(math.atan2(e, n))
    if az < 0.0:
        az += 360.0
    el = math.degrees(math.atan2(u, math.hypot(e, n)))
    return az, el


def to_wgs84(e, n, u):
    """Flat-earth ENU offset → WGS84 (matches firmware enuToGeodetic)."""
    lat = BASE_LAT + n / M_PER_DEG
    lon = BASE_LON + e / (M_PER_DEG * math.cos(math.radians(BASE_LAT)))
    alt = BASE_ALT + u
    return lat, lon, alt


def load_rows():
    """Return [(t, X, Y, Z)] from the CSV, skipping the header comment."""
    rows = []
    with open(CSV_IN, newline="") as f:
        for rec in csv.reader(f):
            if not rec or rec[0].lstrip().startswith("#"):
                continue
            try:
                t, x, y, z = (float(rec[0]), float(rec[1]),
                              float(rec[2]), float(rec[3]))
            except (ValueError, IndexError):
                continue
            rows.append((t, x, y, z))
    rows.sort(key=lambda r: r[0])
    return rows


def resample(rows):
    """Linearly interpolate (X,Y,Z) onto a fixed-HZ time grid → ENU samples."""
    t_end = rows[-1][0]
    n_samples = int(t_end * HZ) + 1
    times = [r[0] for r in rows]
    out = []
    j = 0
    for i in range(n_samples):
        t = i / HZ
        # advance the bracket so times[j] <= t <= times[j+1]
        while j + 1 < len(rows) and times[j + 1] < t:
            j += 1
        t0, x0, y0, z0 = rows[j]
        if j + 1 < len(rows):
            t1, x1, y1, z1 = rows[j + 1]
            f = 0.0 if t1 == t0 else (t - t0) / (t1 - t0)
            f = max(0.0, min(1.0, f))
            x = x0 + (x1 - x0) * f
            y = y0 + (y1 - y0) * f
            z = z0 + (z1 - z0) * f
        else:
            x, y, z = x0, y0, z0
        e = OFFSET_E + x
        n = OFFSET_N + y
        u = z - GROUND_Z
        lat, lon, alt = to_wgs84(e, n, u)
        out.append((t, e, n, u, lat, lon, alt))
    return out


def write_js(samples):
    os.makedirs(os.path.dirname(JS_OUT), exist_ok=True)
    with open(JS_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// AUTO-GENERATED by tools/convert_flight.py -- do not hand-edit.\n")
        f.write("// Source: flight_data.csv | resampled to %d Hz | %d samples.\n"
                % (HZ, len(samples)))
        f.write("// e/n/u = local ENU metres (streamed as `track`); lat/lon/alt = WGS84 truth.\n")
        f.write("window.FLIGHT_TRAJ = {\n")
        f.write("  hz: %d,\n" % HZ)
        f.write("  base: { lat: %.7f, lon: %.7f, alt: %.1f },\n"
                % (BASE_LAT, BASE_LON, BASE_ALT))
        f.write("  samples: [\n")
        for (t, e, n, u, lat, lon, alt) in samples:
            f.write("    {t:%.3f,e:%.2f,n:%.2f,u:%.2f,lat:%.7f,lon:%.7f,alt:%.2f},\n"
                    % (t, e, n, u, lat, lon, alt))
        f.write("  ]\n};\n")


def self_check(samples):
    launch = samples[0]
    landing = samples[-1]
    apogee = max(samples, key=lambda s: s[3])  # max u
    print("Self-check (az / el from base to filtered-truth point):")
    for label, s in (("Launch ", launch), ("Apogee ", apogee), ("Landing", landing)):
        t, e, n, u = s[0], s[1], s[2], s[3]
        az, el = az_el(e, n, u)
        print("  %s t=%7.2fs  e=%8.1f n=%8.1f u=%8.1f  ->  az=%6.1f  el=%5.1f"
              % (label, t, e, n, u, az, el))


def main():
    rows = load_rows()
    samples = resample(rows)
    write_js(samples)
    print("Wrote %s  (%d samples @ %d Hz, %.1f s)"
          % (os.path.relpath(JS_OUT, REPO), len(samples), HZ, samples[-1][0]))
    self_check(samples)
    print("Expected: Launch az 15.9/el 0.0 | Apogee az 97.0/el 76.2 | Landing az 111.8/el 0.0")


if __name__ == "__main__":
    main()
